version: '3.4'
services:
  db:
    image: mysql:latest
    environment: 
      MYSQL_DATABASE: palm_tree
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    networks:
      - palm-tree-docker
  www:
    depends_on:
      - db
    image: php:8.1.6-apache
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - palm-tree-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - palm-tree-docker
networks:
  palm-tree-docker:
    driver: bridge


